index.go
index_test.go

Add a conditional indexer that lets a user specify a function that returns true or false based on the passed object and create an arbitrarily complex index.

Add a conditional indexer

---

index.go
index_test.go
integ_test.go

Make UUIDFieldIndexer support prefix lookups. `UUIDFieldIndex parseString` was not updated to support partial matching do to the performance implications of doing so.

Make UUIDFieldIndex support prefix lookups

---

index.go
index_test.go

Merge parsePartialString and parseString because the new implementation is faster and makes less allocations.

Merge parsePartialString and parseString

---

txn.go
txn_test.go

This adds support for longest prefix matching as needed by https://github.com/hashicorp/consul/pull/1764 (it's not yet integrated over there).
One unfortunate thing is that the null suffixes we add with the `StringFieldIndex` don't work with the algorithm as its currently written - it would need to see if there's a null edge and use that in order to terminate properly. The `LongestPrefix` algorithm is down in the immutable radix tree, so there's no super clean way to get it to understand this.
For my application, I need a custom indexer, similar to the one in the unit test here that can index an empty string, and that will only get added for query templates, so this isn't a big deal. I commented `LongestPrefix` with details about this limitation, and I also made it look for common …

Adds longest prefix matching for custom indexes.

---

index.go
index_test.go

This adds logic to the compound indexer to call `PrefixFromArgs()` on the last sub-indexer. Without this, we don't really get the normal prefix behavior because it calls the regular index on each sub-indexer. While we are in here we also add a check that too many arguments haven't been passed in.

Adds support for calling the prefix method on the last sub-index for a compound index.

---

integ_test.go
memdb.go
txn.go
watch-gen/main.go
watch.go
watch_few.go
watch_test.go

This integrates https://github.com/hashicorp/go-immutable-radix/pull/9 into go-memdb to allow for fine-grained watches based on memdb indexes.

Adds support for fine-grained watches.

---

index.go
index_test.go

This PR fixes an issue where a buffer was undersized for encoding uint
fields. The encoding takes more space than the size of the uint which doesn't really make sense but... https://golang.org/pkg/encoding/binary/
Fixes https://github.com/hashicorp/go-memdb/issues/30

Fix buffer size when encoding uint fields

---

memdb.go
watch-gen/main.go
watch.go
watch_few.go
watch_test.go

This PR adds a Watch method that takes a context rather than a timeout
channel. Moving forward, the new method is the preferred as it avoids
creating a go routine.

Add WatchCtx function

---

watch-gen/main.go
watch.go
watch_few.go
watch_test.go

This PR makes it so the WatchCtx method returns the error from the
context. This simplifies the use of the WatchCtx.

WatchCtx returns error

---

txn.go
txn_test.go

When calling `txn.Delete` on an item that does not exist I don't want to error. Right now I am having to do `if err != nil && err.Error() == "not found"`. This change introduces and uses a new variable `ErrNotFound` so that I can use `if err == memdb.ErrNotFound`

use ErrNotFound for deleting missing item

---

index.go
index_test.go

If a string pointer field is nil, do no return an error but an empty
value.
This helps for the cases when AllowMissing for a field is okay but we
would still like it to be indexed.

fix: allow nil string pointers

---

go.mod
go.sum
txn.go
txn_test.go

This PR builds on https://github.com/hashicorp/go-immutable-radix/pull/24 to allow range scans of memdb indexes.
Lower bound seeks the iterator to the first key that is greater than or equal to some search key. The iterator can then be used to iterate in order over the rest of the values. A caller can simply stop when the result is "to high" to bound the range at the upper end.
An example use case would be using an IntFieldIndex to index over timestamps. `LowerBound` allows finding the first item with a timestamp greater or equal to the start of some time range. The returned iterator can then be iterated until the end of the range of interest.
Due to limitations in iradix, Iterators returned from this method can't be used to watch for changes in the lower bound or range. See …

Add LowerBound to allow for index range scans

---

index.go
index_test.go
txn_test.go

This corrects a bug introduced in
97e94de6e70b3bcdd50849897f5e601e37055947.
If pointer to strings are being Indexed, a nil pointer should not result
in an error only when AllowMissing is set to true for an Index,
otherwise it should rightfully error.

fix: nil strings should be allowed only when AllowMissing is set

---

changeset.go
txn.go
txn_test.go

This PR adds a feature that would be really useful in Consul - change tracking.
It is opt-in so by default it shouldn't affect performance for users who don't need it.
To use change tracking, call `txn.TrackChanges()` on the `Txn` object before mutating values. At the end of the transaction (before or after commit) you can then call `txn.Changes()` to get a list of effective mutations that have occurred during the transaction.
This allows convenient Change Data Capture - the system executing transactions can easily and efficiently get a list of objects changed by the transaction which it can then publish to subscribers who many be interested in changes to that value, without relying on subscribers watching an arbitrary number of channels across potentially hundreds of goroutines. …

Add Change Tracking to MemDB

---

txn.go
txn_test.go

This fixes a bug I found in the recent #70 for an edge case where an object is both inserted and then deleted again in the same transaction.

Fix Changes edge case when inserting and deleting same object in one Txn

---

go.mod
go.sum
txn.go
txn_test.go

This PR introduces a `Snapshot` method to `Txn`.
The new method allows to take a read-only snapshot of an open transaction.
The snapshot will survive the commit or abort of the transaction.
Depends on the feature introduced to `go-immutable-radix` by https://github.com/hashicorp/go-immutable-radix/pull/26. This PR adds a temporary `replace` directive to `go.mod` which will become unnecessary once that PR is merged.

Txn snapshot

---

go.mod
go.sum
txn.go
txn_test.go

go-immutable-radix 1.3.0 introduced a ReverseIterator.
This Commit adds Last(), GetReverse(), ReverseLowerBound()
and other functions to support working with a reverse iterator.

Support go-immutable-radix ReverseIterator

---

filter.go
txn.go
txn_test.go

This is another option for making the code behave correctly in the scenario described in #85 (other option in #86, #88).
This uses the `Txn.Clone` added in https://github.com/hashicorp/go-immutable-radix/pull/26 to clone the mutated index before using it in the iterator. From my reading of that PR this use case matches the one it was intended to solve. We need a read-only copy of the yet-to-be-committed tree. 
This ensures that the iteration is safe, even if modifications are being made during the iteration. However I believe it does come at the cost of some additional allocations. Once `Txn.Clone` is called, any further modifications will require creating new nodes rather then re-using the existing modified ones.
TODO:
Closes #85
Closes #86
Closes #88

Make ResultIteration safe for use after mutation (option 2)

---

index.go
index_test.go

We're using memdb with an id field that's supposed to be monotonically increasing. When the value of the field crosses certain binary-relevant thresholds the ordering gets out of whack. For example on an iteration, 256 shows up before 255.
This PR makes the bytes representation of all types of uints sortable.

Binary representation of UInt indexes should sort properly.

---

index.go
index_test.go

Branched from #108
Also fix a bug when the index is 0 length, found by the property test
Also cleanup the existing test a little bit by using the '\x00' literal

CompoundMultiIndex - Add a benchmark and property test

---

.circleci/config.yml
index.go
index_test.go

Fixes #72 and #106.
This is a continuation of #107. On top of the bug fix, I added a test to express the issue. 
The bug is detailed in #72 and #106. The issue is that the traversal that is done to walk the structure doesn't preserve the path correctly so only a subset of the index would ever be generated. 
Thanks to @WingGithub for the original fix in #107. We wanted to get this in without losing their contribution so I made sure to pull in their commit to my branch.

Fix combination generator in CompoundMultiIndex

---

go.mod
go.sum
index.go
index_test.go

Fix Int indexes to make them sortable.

---

txn.go
watch.go

The behaviour of `First/Last` methods can be verified using the following simple test:
```go
type Job struct {
ID string
}
func TestRepro(t *testing.T) {
dbSchema := &memdb.DBSchema{
Tables: map[string]*memdb.TableSchema{
"jobs": {
Name: "jobs",
Indexes: map[string]*memdb.IndexSchema{
"id": {
Name:    "id",
Unique:  true,
Indexer: &memdb.StringFieldIndex{Field: "ID"},
},
},
},
},
}
db, err := memdb.NewMemDB(dbSchema)
if err != nil {
t.Fatal(err)
}
txn0 := db.Txn(false)
txn1 := db.Txn(true)
t.Cleanup(txn1.Abort)
err = txn1.Insert("jobs", &Job{
ID: "one",
})
if err != nil {
t.Fatal(err)
}
txn1.Commit()
obj, err := txn0.First("jobs", "id")
if err != nil {
t.Fatal(err)
}
t.Logf("received obj = %#v", obj)
}
```
```
go test ./internal/scheduler -run=TestRepro -v -count=1
=== RUN   TestRepro …
```

Clarify usage of WatchSet methods and behaviour of First/Last

---

txn.go

This behaviour is documented on an unexported function, but it doesn't show up in the godoc. I've attempted to move it to all the exported functions that call `getIndexValue`

Document _prefix index matching for queries

---

watch.go

This PR attempts to clarify the godoc for `WatchSet`. Specifically I want to document that `WatchSet.WatchCtx` only returns an error if the context is what caused it to unblock.  Consul depends on this behaviour, and we don't want it to change accidentally. I made a few other edits while I was reading over the docs. Happy to make changes if my first draft is not clear.

Document error return value of WatchSet.WatchCtx

---

memdb.go

This is to support more straightforward integration with a UI, also mentioned in https://github.com/hashicorp/go-memdb/pull/57

introduce MemDB.DBSchema() method for introspection

---

isolation_test.go

Extend the unit tests to cover the expected isolation levels for avoiding dirty reads, non-repeatable reads, and phantom reads.
These tests are intended to be demonstrative rather than exhaustive. They provide a guide for developers as to what behaviors to expect from applications consuming the library rather than robustly verifying the behavior under load and high concurrency. That is, they can show that an implementation is grossly incorrect but cannot show that an implementation is correct.
(I've opened this PR mostly to anchor an internal discussion for proposed iterator changes.)

testing: demonstrate expected isolation properties

---

.github/dependabot.yml
CHANGELOG.md

- As per the memo: https://go.hashi.co/memo/eng-004,
Enabling the dependabot for identifying and updating the security and version updates in the repositories rather handling it manually.
- Adding the CHANGELOG.md file to maintain standardisation across OSS core libraries

IND-3834 dependabot enabling, changelog added
